# Generated by Django 2.1.4 on 2019-01-19 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acticle', '0003_auto_20190117_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='keywoords',
            new_name='keywords',
        ),
        migrations.AlterField(
            model_name='article',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_id', to='acticle.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='super_id', to='acticle.Category'),
        ),
    ]
