# Generated by Django 2.1.4 on 2019-01-19 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acticle', '0005_auto_20190119_1612'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
