# Generated by Django 2.1.4 on 2019-01-19 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190119_1612'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]
