# Generated by Django 2.1.4 on 2019-01-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_num',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
